# -*- coding: utf-8 -*-
"""food_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_fh_T-fHKNhQ9dWdWw4qM9XmC8FzGubR

# Yemek Sınıflandırıcı - TensorFlow
6 sınıf: Beyti, D.Çorbası, M.Çorbası, Sarma, Su Böreği, Tiramisu
"""

# Dataset indir
from google.colab import drive
drive.mount('/content/drive')
!cp /content/drive/MyDrive/foods.zip .
!unzip foods.zip

import tensorflow as tf
import matplotlib.pyplot as plt

img_height, img_width = 64, 64
batch_size = 20

train_ds = tf.keras.utils.image_dataset_from_directory(
    "foods/train",
    image_size=(img_height, img_width),
    batch_size=batch_size
)
val_ds = tf.keras.utils.image_dataset_from_directory(
    "foods/validation",
    image_size=(img_height, img_width),
    batch_size=batch_size
)
test_ds = tf.keras.utils.image_dataset_from_directory(
    "foods/test",
    image_size=(img_height, img_width),
    batch_size=batch_size
)

# Örnek görselleri görselleştir
class_names = ["Beyti", "D.Çorbası", "M.Çorbası", "Sarma", "Su Böreği", "Tiramisu"]
plt.figure(figsize=(10, 10))
for images, labels in train_ds.take(1):
    for i in range(18):
        ax = plt.subplot(3, 6, i + 1)
        plt.imshow(images[i].numpy().astype("uint8"))
        plt.title(class_names[labels[i]])
        plt.axis("off")

# Model mimarisi
model = tf.keras.Sequential(
    [
        # Data Augmentation
        tf.keras.layers.RandomFlip("horizontal"),
        tf.keras.layers.RandomRotation(0.1),
        tf.keras.layers.RandomZoom(0.1),

        # Preprocessing
        tf.keras.layers.Rescaling(1./255),

        # Conv blokları
        tf.keras.layers.Conv2D(64, 3, activation="relu"),
        tf.keras.layers.MaxPooling2D(),
        tf.keras.layers.Conv2D(64, 3, activation="relu"),
        tf.keras.layers.MaxPooling2D(),
        tf.keras.layers.Conv2D(64, 3, activation="relu"),
        tf.keras.layers.MaxPooling2D(),

        # Classifier
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.3),
        tf.keras.layers.Dense(6)
    ]
)

# Compile ve eğitim
model.compile(
    optimizer=tf.keras.optimizers.Adam(),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=['accuracy']
)

early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=30,
    callbacks=[early_stopping]
)

# Test seti değerlendirme
model.evaluate(test_ds)

import numpy
from scipy.special import softmax

plt.figure(figsize=(15, 10))
for images, labels in test_ds.take(1):
    classifications = model(images)

for i in range(18):
    ax = plt.subplot(3, 6, i + 1)
    plt.imshow(images[i].numpy().astype("uint8"))

    probs = softmax(classifications[i])
    index = numpy.argmax(probs)
    confidence = probs[index]

    if confidence < 0.7:
        pred_label = "?"
    else:
        pred_label = class_names[index]

    real_label = class_names[labels[i]]
    color = "green" if pred_label == real_label else "red"

    plt.title(f"T: {pred_label}\nG: {real_label}", color=color, fontsize=8)
    plt.axis("off")

plt.tight_layout()
plt.show()

# TFLite'a dönüştür ve kaydet
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

with open("model.tflite", 'wb') as f:
    f.write(tflite_model)